package Core;

import java.io.File;

public class ArquivoAcoes extends javax.swing.JFrame {

    /**
     * Creates new form ArquivoAcoes
     */
    public ArquivoAcoes(File arquivo) {
        initComponents();
        InicializarComboGenero();
        this.setLocationRelativeTo(null);
        tbTitulo.setText(UtilsIO.ReadData(arquivo, 30));
        tbArtista.setText(UtilsIO.ReadData(arquivo, 30));
        tbAlbum.setText(UtilsIO.ReadData(arquivo, 30));
        tbAno.setText(UtilsIO.ReadData(arquivo, 4));
        tbComentario.setText(UtilsIO.ReadData(arquivo, 28));
        UtilsIO.ReadData(arquivo, 1);
        tbNrFaixa.setText(UtilsIO.ReadData(arquivo, 1));
        preencheGenero(UtilsIO.ReadData(arquivo, 1));
    }

    public ArquivoAcoes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void preencheGenero(String genero) {
        if (UtilsIO.isNumber(genero)) {
            if (Integer.parseInt(genero) <= UtilsIO.genresLastIndex) {
                cbGenero.setSelectedIndex(Integer.parseInt(genero));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tbTitulo = new javax.swing.JTextField();
        tbArtista = new javax.swing.JTextField();
        tbAlbum = new javax.swing.JTextField();
        tbAno = new javax.swing.JTextField();
        tbComentario = new javax.swing.JTextField();
        tbNrFaixa = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo:");

        jLabel2.setText("Artista:");

        jLabel3.setText("Álbum:");

        jLabel4.setText("Ano:");

        jLabel5.setText("Comentário:");

        jLabel6.setText("Nr.Faixa:");

        jLabel7.setText("Gênero:");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar alterações");

        tbAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAnoActionPerformed(evt);
            }
        });

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(75, 75, 75)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(tbArtista)
                            .addComponent(tbAlbum)
                            .addComponent(tbAno)
                            .addComponent(tbComentario)
                            .addComponent(tbNrFaixa)
                            .addComponent(cbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNrFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArquivoEscolha escolha = new ArquivoEscolha();
        escolha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        tbTitulo.setText("");
        tbArtista.setText("");
        tbAlbum.setText("");
        tbAno.setText("");
        tbComentario.setText("");
        tbNrFaixa.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArquivoAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArquivoAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArquivoAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArquivoAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArquivoAcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tbAlbum;
    private javax.swing.JTextField tbAno;
    private javax.swing.JTextField tbArtista;
    private javax.swing.JTextField tbComentario;
    private javax.swing.JTextField tbNrFaixa;
    private javax.swing.JTextField tbTitulo;
    // End of variables declaration//GEN-END:variables

    private void InicializarComboGenero() {
        cbGenero.removeAllItems();
        cbGenero.addItem("Blues");
        cbGenero.addItem("Classic Rock");
        cbGenero.addItem("Country");
        cbGenero.addItem("Dance");
        cbGenero.addItem("Disco");
        cbGenero.addItem("Funk");
        cbGenero.addItem("Grunge");
        cbGenero.addItem("Hip-Hop");
        cbGenero.addItem("Jazz");
        cbGenero.addItem("Metal");
        cbGenero.addItem("New Age");
        cbGenero.addItem("Oldies");
        cbGenero.addItem("Other");
        cbGenero.addItem("Pop");
        cbGenero.addItem("R&B");
        cbGenero.addItem("Rap");
        cbGenero.addItem("Reggae");
        cbGenero.addItem("Rock");
        cbGenero.addItem("Techno");
        cbGenero.addItem("Industrial");
        cbGenero.addItem("Alternative");
        cbGenero.addItem("Ska");
        cbGenero.addItem("Death Metal");
        cbGenero.addItem("Pranks");
        cbGenero.addItem("Soundtrack");
        cbGenero.addItem("Euro-Techno");
        cbGenero.addItem("Ambient");
        cbGenero.addItem("Trip-Hop");
        cbGenero.addItem("Vocal");
        cbGenero.addItem("Jazz+Funk");
        cbGenero.addItem("Fusion");
        cbGenero.addItem("Trance");
        cbGenero.addItem("Classical");
        cbGenero.addItem("Instrumental");
        cbGenero.addItem("Acid");
        cbGenero.addItem("House");
        cbGenero.addItem("Game");
        cbGenero.addItem("Sound Clip");
        cbGenero.addItem("Gospel");
        cbGenero.addItem("Noise");
        cbGenero.addItem("AlternRock");
        cbGenero.addItem("Bass");
        cbGenero.addItem("Soul");
        cbGenero.addItem("Punk");
        cbGenero.addItem("Space");
        cbGenero.addItem("Mediative");
        cbGenero.addItem("Instrumental Pop");
        cbGenero.addItem("Instrumental Rock");
        cbGenero.addItem("Ethnic");
        cbGenero.addItem("Gothic");
        cbGenero.addItem("Darkwave");
        cbGenero.addItem("Techno-Industrial");
        cbGenero.addItem("Electronic");
        cbGenero.addItem("Pop-Folk");
        cbGenero.addItem("Eurodance");
        cbGenero.addItem("Dream");
        cbGenero.addItem("Southern Rock");
        cbGenero.addItem("Comedy");
        cbGenero.addItem("Cult");
        cbGenero.addItem("Gangsta");
        cbGenero.addItem("Top 40");
        cbGenero.addItem("Christian Rap");
        cbGenero.addItem("Pop/Funk");
        cbGenero.addItem("Jungle");
        cbGenero.addItem("Native American");
        cbGenero.addItem("Cabaret");
        cbGenero.addItem("New Wave");
        cbGenero.addItem("Psychadelic");
        cbGenero.addItem("Rave");
        cbGenero.addItem("Showtunes");
        cbGenero.addItem("Trailer");
        cbGenero.addItem("Lo-Fi");
        cbGenero.addItem("Tribal");
        cbGenero.addItem("Acid Punk");
        cbGenero.addItem("Acid Jazz");
        cbGenero.addItem("Polka");
        cbGenero.addItem("Retro");
        cbGenero.addItem("Musical");
        cbGenero.addItem("Rock & Roll");
        cbGenero.addItem("Hard Rock");
    }
}
